### ISSUE TITLE
Export model gives you exception StopIteration

### ISSUE THREAD

**Issue by Solitaryo** [bmihelac/django-import-export#179]
I can't figure it out, but i have import-export running in 2 models, 1 fails and 1 works, and the implementation is the same, i got this error:
StopIteration at blabla/blablab/blabla/export
No exception message supplied
![error](https://cloud.githubusercontent.com/assets/5264161/5135764/f373c1d8-70d9-11e4-883c-dd5d6be47e85.png)

**Comment by bmihelac** [comment]
If this issue persist please reopen.

**Comment by rhunwicks** [comment]
I am testing an upgrade of our working Django 1.6 to Django 1.7 and we are also getting this error on many or our tests. I wonder if it is related to custom managers. We will investigate and update here.

**Comment by rhunwicks** [comment]
In our case, it was caused by an incorrectly-specified, read-only field for a outputting a value from the child of a parent accessed by a foreign key. The `attribute` used the `__` notation to go up to the parent and then back down to the other child, but it stopped at the name of the field in the parent. The result of this was that the `value` that the `Widget` is trying to render is a `RelatedManager`. The `Widget` tries to `force_text` the `value` and that used to work on Django 1.6 but doesn't work on Django 1.7. It's an error in our code though, because obviously it doesn't make sense to render the related manager anyway.

**Comment by bmihelac** [comment]
Thanks for report @rhunwicks
