### ISSUE TITLE
Export order

### ISSUE THREAD

**Issue by jeberger** [bmihelac/django-import-export#210]
Is there a way to specify a partial export order ? For example, I'd like to specify that the first two columns should be "id" and "name", then I'd like to have all remaining fields in whatever order.

Currently I have two options: 
 - Specify `export_order` in the resource's meta object, but any field that is not listed will not be included;
 - Not specify `export_order` in which case the export starts with the fields declared explicitly in the resource in no particular order followed by introspected fields in the order they were declared in the model.

Ideally, what I would like is to have introspected fields first in order of declaration, then explicit fields. Since other applications may have different requirements, I would be happy with specifying a couple of fields explicitly in `export_order` so that those fields will come first and in the specified order, then have any remaining fields come after in no particular order.

**Comment by bmihelac** [comment]
Since you can access all fields in ``resource.fields`` ordered dict so it should be easy enough to add fields not in ``export_order`` to the end of the list.  This would happen in``get_export_order`` .
PR would be welcomed

**Comment by rhunwicks** [comment]
I wonder if this needs a slight amendment.

I have a `Resource` where I am importing a field using a column with a different name:

```python 
class MyResource(ModelResource):
    set = fields.Field(column_name='set', attribute='name')
```

The column `name` exists in the `dataset` but is not the one I want to import from. With the previous version of the code, the `name` column in the `dataset` was ignored because I didn't include in the export order. However, now it gets included, and it gets included after my `set` field, with the result that in `import_obj` the value from `set` is incorrectly overwritten with the value from `name`.

I see three possible solutions:

1. We change the code so that `get_export_order()` only adds the field if it is not already in `self._meta.export_order` AND its attribute is also different to all the field in `export_order`.
1. We change `import_obj` so that it iterates over the results of `get_fields()` (which is the same as the fields returned by `get_export_order()`) in reverse, so that any fields we added automatically at the end have their values overwritten by the declared field if the attributes are the same. I think this would work, but it smacks of "magic"
1. We update the documentation to make it clear that you need to use `exclude` in addition to `fields` if there are columns in the `dataset` you want to ignore.

**Comment by bmihelac** [comment]
@rhunwicks ``get_export_order`` should only impact on the order of fields and not on if the fields are included or not, agree?

**Comment by rhunwicks** [comment]
I agree, which I think means that we need to change `get_fields()` so it's not based on `get_export_order()`.

I wonder if many people have relied on `export_order` to control what fields get included, because that's how it worked. I know that's what I was doing - it seemed more DRY than creating both `fields` and `export_order`.

I think that even from the point of view of exporting, we should probably implement Option 1. I can't see why you would want a field in the export twice, once with its Field name and once with its own Attribute name, which is I think what must be happening now.

**Comment by rhunwicks** [comment]
Reading my last comment again, I think may be we should be leaving `get_fields()` based on `export_order` and implementing 1. so that we don't break existing code.
